name: Test build wheels

on:
  workflow_dispatch:

jobs:
  build_many_wheels:
    name: Build wheels on standard linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "*manylinux*"
          CIBW_SKIP: cp36* cp37* pp* *i686*
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD: >
            pip install -U pybind11-global &&
            pip list
          # CIBW_BEFORE_TEST: pip install -U pytest pytest-xdist pytest-cov
          # CIBW_TEST_COMMAND: pytest {package}/tests

      - uses: actions/upload-artifact@v4
        with:
          name: manylinux-artifacts
          path: ./wheelhouse/*.whl

  build_musl_wheels:
    name: Build wheels on musl linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "*musllinux*"
          CIBW_SKIP: cp36* cp37* pp* *i686*
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD: >
            pip install -U pybind11-global &&
            pip list
          # CIBW_BEFORE_TEST: pip install -U pytest pytest-xdist pytest-cov
          # CIBW_TEST_COMMAND: pytest {package}/tests

      - uses: actions/upload-artifact@v4
        with:
          name: musllinux-artifacts
          path: ./wheelhouse/*.whl

  build_macosx_wheels:
    name: Build wheels on macosx
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "*macosx*"
          CIBW_SKIP: cp36* cp37* pp* *i686*
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD: >
            pip install -U pybind11-global &&
            pip list
          # CIBW_BEFORE_TEST: pip install -U pytest pytest-xdist pytest-cov
          # CIBW_TEST_COMMAND: pytest {package}/tests

      - uses: actions/upload-artifact@v4
        with:
          name: macosx-artifacts
          path: ./wheelhouse/*.whl

